### PR TITLE
Re-license to Apache 2.0

### PR DESCRIPTION
**Pull request by SupremeMortal**
Re-license under a more permissive license (similar to MIT)
All contributors must agree for the license to be changed.
@wode490390 @AJ-Ferguson @Creeperface01

### CODE REVIEW

**Comment by Creeperface01** [comment]
Agree

**Comment by wode490390** [comment]
I agree.

**Comment by AJ-Ferguson** [comment]
Agree

**Comment by SupremeMortal** [comment]
Thanks

**Pull request merged**
