### PR TITLE
Add 1.21.40 support

### PR DESCRIPTION
**Pull request by Kaooot**

### CODE REVIEW

**Comment by smartcmd** [comment]
Just curious, how do you know that something is deprecated?

**Comment by Kaooot** [comment]
@smartcmd I know that because it is mentioned in the protocol documentation https://github.com/Mojang/bedrock-protocol-docs/pull/15

**Comment by onebeastchris** [comment]
Would be neat if you could also update the protocol table on the readme :p

**Comment by Alemiz112** [comment]
Merged in 43b1c8727206eb3cf8ba62d0d7650662ff67a1f9. Thanks for the PR!

**Pull request closed without merging**
