### PR TITLE
[DNM] [WIP] Update NukkitX Network Dependency

### PR DESCRIPTION
**Pull request by c-wolfe**
Update Network dependency from v1.3.1 to v1.4.2

### CODE REVIEW

**Comment by Creeperface01** [comment]
Do you realize that more than version number has changed?

**Comment by Creeperface01** [comment]
Do you realize that more than version number was changed?

**Comment by c-wolfe** [comment]
Yes, yes I do

**Comment by SupremeMortal** [comment]
I have some other changes to add then I'll update here.

**Pull request closed without merging**
