### PR TITLE
Fix ForceExperimentalGameplay option

### PR DESCRIPTION
**Pull request by lt-name**
I use nk testing, and it seems that there is no need to send an additional boolean value.

### CODE REVIEW

**Comment by Alemiz112** [comment]
Hi, this is not correct. In this case, if the flag value is `true`, it writes two booleans (don't ask me why 😅).
See decompiled game code:
image

**Comment by lt-name** [comment]
ok, got it, thanks for your answer

**Comment by CoolLoong** [comment]
I think this is still an error, which is the result of using ida decompilation in Windows 1.20.30 version of bds.
`serialize<LevelSettings>::write`
image
At the same time, I use the 594 version protocol library to set StartGamePacket.
`startGamePacket.setForceExperimentalGameplay(OptionalBoolean.of(true));` 
When the player enter the server
image

**Comment by lt-name** [comment]
According to my test results on nk and modified version of wdpe, it does have problems
After the current protocol library is enabled in experimental mode, the client will report an error.

**Comment by Alemiz112** [comment]
Hi, I just checked the IDA analyzed code on 1.20.30 for this again. But I can not seems to find anything that would match what you can see there.
I am looking at `serialize<LevelSettings>::write(const LevelSettings_1 *val, BinaryStream *stream)`, which has following contents:
image

I also checked `serialize<LevelSettings>::read(Bedrock::Result<LevelSettings,std::error_code>_0 *retstr, ReadOnlyBinaryStream *stream)` to see if there is something different, but it does basically the same - if optional is present, writeBool(true) then writeBool(true) again else writeBool(false) only once.

**Comment by CoolLoong** [comment]
I'm not sure what caused the difference in our decompiled code. Are you using the Linux version?

**Comment by CoolLoong** [comment]
I'm not sure what caused the difference in our decompiled code. Are you using the Linux version?

**Comment by CoolLoong** [comment]
But regardless of the decompiled code, you can test the 594 protocol and it will not be able to enter the server.

**Pull request closed without merging**
