### PR TITLE
Add 1.21.30 support

### PR DESCRIPTION
**Pull request by Kaooot**
New Packets:
[CameraAimAssist](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R7) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-5b0911f4da0a61a7cd89fc159cacbbd5058d905a869e175ee8e056b42bb70ab0R8)
[ContainerRegistryCleanup](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R13) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-bf79a95229de109cb69a99ebfceb15529340237ca5ba0a6b2a2cd99221ab9b50R8)

Changed Packets:
[EmotePacket](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R19) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-e52dfa03dd2920d87554a06b6efe287999e664d08c1b2e357e9efa0f8c1bbd18R9)
[InventoryContentPacket](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R22) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-fdd262d787cbc6238d36b8d2662908cef38b0b20b848e3b377b6812a890299e7R9)
[InventorySlotPacket](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R27) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-e698d2c470852b268918a83d08e575de9b8fef855503b7adb1c913b780ee86ccR9)
[ResourcePacksInfoPacket](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R32) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-801c8f633fb2b8e165696fae491abad4fdeb0215d63d9f2a98a62152c6b90b18R8)
[TransferPacket](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R37) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-52000933e03ed6eddf7219825811697dbe6c6ec676c63bc0046c722ac98baf6dR8)
[UpdateAttributesPacket](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R40) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-6d145302c40844f87ee30f6c141ceb0a2254deab62abbb4380baa7204820e08eR14)

Changed Types:
[CameraPreset](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R52) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-b33303cd2d985c6bd75260c50e98f42160b1f86be7b2e8a00ceada6a153bd598R12)
[FullContainerName](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R57) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-5044c588f9ad3caa4fda6cb0fbfd1416d949d8d077a32ddd74df0a56b18d5efaR19)

New Enums:
[CameraAimAssistPacket::Action](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R64) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-0fc483046834ac476af954d99589d24d12fc8c66b733cdf05b0154f50a72a58dR33)
[CameraAimAssistPacket::TargetMode](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R68) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-0fc483046834ac476af954d99589d24d12fc8c66b733cdf05b0154f50a72a58dR28)

Changed Enums:
[Connection::DisconnectFailReason](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R79) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-47e3f111c4991f4179eeac3d92f59625c4199b160f035baab808a8b7ffb438a2R124)
[ContainerID](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R82) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-4dc101fb6c432508152b69217fe34e4a5dc637022b1ef9e9144f7b2ea75b9576R44)
[PlayerAuthInputPacket::InputData](https://github.com/Mojang/bedrock-protocol-docs/commit/2a93b3dc8c81a089b437cc071e0275e4ebe5f8b0#diff-27ec401e8db70aae7057079d9817ba9909b51430823ed3ea37247b599a99d951R166) | [Implementation](https://github.com/CloudburstMC/Protocol/pull/254/commits/c6871bf3b55824fbeb0b41fcf2011a0cb16182de#diff-9945fa8ac5e0a3f469bb31b542f889749e0e54a94a7288b7c13e401ac3cc6de5R92)

### CODE REVIEW

**Comment by Buddelbubi** [comment]
Seems to be incomplete. For example ResourcePacksInfo removed the BehaviourPacket field. We tried to implement your changes in PNX, but we get a Broken Packet Screen on join.

**Comment by Kaooot** [comment]
@Buddelbubi I checked it again and I think it works fine, but I found a few bugs in your implementation:
- Changes in UpdateAttributesPacket are missing
- Changes in CameraPreset type are missing
- mBehaviorPacks is not removed from ResourcePacksInfoPacket: https://github.com/PowerNukkitX/PowerNukkitX/commit/b63153923416e104904ab36ee988ab7ea4e895c7#diff-3400a7ff4bc3883e451fc6754ecb64116d75d39607efe35af6c73ff56320f421L44
- The mDynamicId should be an optional unsigned 32 bit integer: https://github.com/PowerNukkitX/PowerNukkitX/commit/e8e4b861a24e6a29655a36b65fa9720c437b7147#diff-d1d0dd7ef20d63d79e43983549170fc9bf665e31427fca1f7cf8cdbe72faca4bR929
- Your sound ids are wrong (IMITATE_BOGGED should be 510 and VAULT_REJECT_REWARDED_PLAYER is 530): https://github.com/PowerNukkitX/PowerNukkitX/blob/88efd17226da562bbfbcc48a6e7a69f651d9d52e/src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java#L546

**Comment by Buddelbubi** [comment]
> @Buddelbubi I checked it again and I think it works fine, but I found a few bugs in your implementation:
> 
>     * Changes in UpdateAttributesPacket are missing
> 
>     * Changes in CameraPreset type are missing
> 
>     * mBehaviorPacks is not removed from ResourcePacksInfoPacket: [PowerNukkitX/PowerNukkitX@b631539#diff-3400a7ff4bc3883e451fc6754ecb64116d75d39607efe35af6c73ff56320f421L44](https://github.com/PowerNukkitX/PowerNukkitX/commit/b63153923416e104904ab36ee988ab7ea4e895c7#diff-3400a7ff4bc3883e451fc6754ecb64116d75d39607efe35af6c73ff56320f421L44)
> 
>     * The mDynamicId should be an optional unsigned 32 bit integer: [PowerNukkitX/PowerNukkitX@e8e4b86#diff-d1d0dd7ef20d63d79e43983549170fc9bf665e31427fca1f7cf8cdbe72faca4bR929](https://github.com/PowerNukkitX/PowerNukkitX/commit/e8e4b861a24e6a29655a36b65fa9720c437b7147#diff-d1d0dd7ef20d63d79e43983549170fc9bf665e31427fca1f7cf8cdbe72faca4bR929)
> 
>     * Your sound ids are wrong (IMITATE_BOGGED should be 510 and VAULT_REJECT_REWARDED_PLAYER is 530): https://github.com/PowerNukkitX/PowerNukkitX/blob/88efd17226da562bbfbcc48a6e7a69f651d9d52e/src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java#L546

Oh okay. Zhank you. We probably forgot to push the InfoPacket, but the other stuff is probably our fault. Sorry for the missunderstanding. Love your work.

**Comment by Alemiz112** [comment]
Completed in ea983c137671bbe3feba418a356fafc9b10d7751. Thanks for contribution.

**Pull request closed without merging**
